interface ZIF_I_01_BOOKINGTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_01_BOOKINGTP,
 CREATE_ZI_01_BOOKINGTP         TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1AB847',
 DELETE_ZI_01_BOOKINGTP         TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1B3847',
 LOCK_ZI_01_BOOKINGTP           TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E19F847',
 SAVE_ZI_01_BOOKINGTP           TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1BB847',
 UNLOCK_ZI_01_BOOKINGTP         TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1A3847',
 UPDATE_ZI_01_BOOKINGTP         TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1AF847',
 VALIDATE_ZI_01_BOOKINGTP       TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9FF3B2CE7E1B7847',
      END OF ZI_01_BOOKINGTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_01_BOOKINGTP,
        BEGIN OF LOCK_ZI_01_BOOKINGTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_01_BOOKINGTP,
        BEGIN OF UNLOCK_ZI_01_BOOKINGTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_01_BOOKINGTP,
      END OF ZI_01_BOOKINGTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_01_BOOKINGTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EEC9FF3B2CE7E1C9847',
      END OF ZI_01_BOOKINGTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_01_BOOKINGTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E19D847',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E199847',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E1A9847',
      END OF ZI_01_BOOKINGTP,
      BEGIN OF ZI_01_BOOKINGTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E1C1847',
      END OF ZI_01_BOOKINGTP_LOCK,
      BEGIN OF ZI_01_BOOKINGTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E1BF847',
      END OF ZI_01_BOOKINGTP_MESSAGE,
      BEGIN OF ZI_01_BOOKINGTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9FF3B2CE7E1C3847',
      END OF ZI_01_BOOKINGTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_01_BOOKINGTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_01_BOOKINGTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EEC9FF3B2CE7E18F847' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_01_BOOKINGTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_01_BOOKINGTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EEC9FF3B2CE7E1CB847',
      END OF ZI_01_BOOKINGTP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_01_BOOKINGTP                TYPE /BOBF/OBM_GROUP_KEY VALUE '005056044E851EEC9FF3B2CE7E287847',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_01_BOOKINGTP                TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9FF3B2CE7E193847',
 ZI_01_BOOKINGTP_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9FF3B2CE7E19B847',
 ZI_01_BOOKINGTP_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9FF3B2CE7E197847',
 ZI_01_BOOKINGTP_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9FF3B2CE7E1A7847',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_01_BOOKINGTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CONNID                         TYPE STRING VALUE 'CONNID',
  FLDATE                         TYPE STRING VALUE 'FLDATE',
  BOOKID                         TYPE STRING VALUE 'BOOKID',
  CUSTOMID                       TYPE STRING VALUE 'CUSTOMID',
  CUSTTYPE                       TYPE STRING VALUE 'CUSTTYPE',
  SMOKER                         TYPE STRING VALUE 'SMOKER',
  LUGGWEIGHT                     TYPE STRING VALUE 'LUGGWEIGHT',
  WUNIT                          TYPE STRING VALUE 'WUNIT',
  INVOICE                        TYPE STRING VALUE 'INVOICE',
  CLASS                          TYPE STRING VALUE 'CLASS',
  FORCURAM                       TYPE STRING VALUE 'FORCURAM',
  FORCURKEY                      TYPE STRING VALUE 'FORCURKEY',
  LOCCURAM                       TYPE STRING VALUE 'LOCCURAM',
  LOCCURKEY                      TYPE STRING VALUE 'LOCCURKEY',
  ORDER_DATE                     TYPE STRING VALUE 'ORDER_DATE',
  COUNTER                        TYPE STRING VALUE 'COUNTER',
  AGENCYNUM                      TYPE STRING VALUE 'AGENCYNUM',
  CANCELLED                      TYPE STRING VALUE 'CANCELLED',
  RESERVED                       TYPE STRING VALUE 'RESERVED',
  PASSNAME                       TYPE STRING VALUE 'PASSNAME',
  PASSFORM                       TYPE STRING VALUE 'PASSFORM',
  PASSBIRTH                      TYPE STRING VALUE 'PASSBIRTH',
  ORDERDATE                      TYPE STRING VALUE 'ORDERDATE',
      END OF ZI_01_BOOKINGTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_01_BOOKINGTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EEC9FF3B2CE7E195847',
      END OF ZI_01_BOOKINGTP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_01_BOOKINGTP,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '005056044E851EEC9FF3B2CE7E1D5847',
      END OF ZI_01_BOOKINGTP,
    END OF SC_VALIDATION .
endinterface.
