interface ZIF_C_01_BOOKINGS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_01_BOOKINGS,
 CANCEL_BOOKING                 TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE944398AF3CEE',
 CREATE_ZC_01_BOOKINGS          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA60BB64',
 DELETE_ZC_01_BOOKINGS          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA613B64',
 LOCK_ZC_01_BOOKINGS            TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA5FFB64',
 SAVE_ZC_01_BOOKINGS            TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA61BB64',
 UNLOCK_ZC_01_BOOKINGS          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA603B64',
 UPDATE_ZC_01_BOOKINGS          TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA60FB64',
 VALIDATE_ZC_01_BOOKINGS        TYPE /BOBF/ACT_KEY VALUE '005056044E851EDC9FDE3DECAA617B64',
      END OF ZC_01_BOOKINGS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_01_BOOKINGS,
        BEGIN OF LOCK_ZC_01_BOOKINGS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZC_01_BOOKINGS,
        BEGIN OF UNLOCK_ZC_01_BOOKINGS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZC_01_BOOKINGS,
      END OF ZC_01_BOOKINGS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_01_BOOKINGS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EDC9FDE3DECAA629B64',
      END OF ZC_01_BOOKINGS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_01_BOOKINGS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA5FDB64',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA5F9B64',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA609B64',
      END OF ZC_01_BOOKINGS,
      BEGIN OF ZC_01_BOOKINGS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA621B64',
      END OF ZC_01_BOOKINGS_LOCK,
      BEGIN OF ZC_01_BOOKINGS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA61FB64',
      END OF ZC_01_BOOKINGS_MESSAGE,
      BEGIN OF ZC_01_BOOKINGS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EDC9FDE3DECAA623B64',
      END OF ZC_01_BOOKINGS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_01_BOOKINGS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_01_BOOKINGS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EDC9FDE3DECAA5EFB64' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_01_BOOKINGS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZC_01_BOOKINGS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EDC9FDE3DECAA62BB64',
      END OF ZC_01_BOOKINGS,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZC_01_BOOKINGS                 TYPE /BOBF/OBM_GROUP_KEY VALUE '005056044E851EDC9FDE3DECAA6E1B64',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_01_BOOKINGS                 TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDC9FDE3DECAA5F3B64',
 ZC_01_BOOKINGS_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDC9FDE3DECAA5FBB64',
 ZC_01_BOOKINGS_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDC9FDE3DECAA5F7B64',
 ZC_01_BOOKINGS_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EDC9FDE3DECAA607B64',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_01_BOOKINGS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CONNID                         TYPE STRING VALUE 'CONNID',
  FLDATE                         TYPE STRING VALUE 'FLDATE',
  BOOKID                         TYPE STRING VALUE 'BOOKID',
  CUSTOMID                       TYPE STRING VALUE 'CUSTOMID',
  CUSTTYPE                       TYPE STRING VALUE 'CUSTTYPE',
  SMOKER                         TYPE STRING VALUE 'SMOKER',
  LUGGWEIGHT                     TYPE STRING VALUE 'LUGGWEIGHT',
  WUNIT                          TYPE STRING VALUE 'WUNIT',
  INVOICE                        TYPE STRING VALUE 'INVOICE',
  CLASS                          TYPE STRING VALUE 'CLASS',
  FORCURAM                       TYPE STRING VALUE 'FORCURAM',
  FORCURKEY                      TYPE STRING VALUE 'FORCURKEY',
  LOCCURAM                       TYPE STRING VALUE 'LOCCURAM',
  LOCCURKEY                      TYPE STRING VALUE 'LOCCURKEY',
  ORDER_DATE                     TYPE STRING VALUE 'ORDER_DATE',
  COUNTER                        TYPE STRING VALUE 'COUNTER',
  AGENCYNUM                      TYPE STRING VALUE 'AGENCYNUM',
  CANCELLED                      TYPE STRING VALUE 'CANCELLED',
  RESERVED                       TYPE STRING VALUE 'RESERVED',
  PASSNAME                       TYPE STRING VALUE 'PASSNAME',
  PASSFORM                       TYPE STRING VALUE 'PASSFORM',
  PASSBIRTH                      TYPE STRING VALUE 'PASSBIRTH',
  ORDERDATE                      TYPE STRING VALUE 'ORDERDATE',
  INVOICECRITICALLY              TYPE STRING VALUE 'INVOICECRITICALLY',
      END OF ZC_01_BOOKINGS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_01_BOOKINGS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EDC9FDE3DECAA5F5B64',
      END OF ZC_01_BOOKINGS,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZC_01_BOOKINGS,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '005056044E851EDC9FDE3DECAA635B64',
      END OF ZC_01_BOOKINGS,
    END OF SC_VALIDATION .
endinterface.
